import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight, Brain, Download, Eye, Github, Mic, ShieldCheck, Waves } from "lucide-react"

const repositoryUrl = "https://github.com/xRetr00/Marvi-OS"
const sections = [
  { icon: Mic, title: "Voice", text: "Talk to Marvi naturally using a wake word and conversational voice interaction. It is designed for quick, ambient moments instead of long sessions in a window." },
  { icon: Eye, title: "Vision", text: "Marvi brings visual context into the conversation, helping you understand what is on your screen or happening around you when words are not enough." },
  { icon: Brain, title: "Memory", text: "The memory layer gives conversations continuity. You decide what should be remembered and keep the relationship with your assistant personal." },
  { icon: Waves, title: "Dynamic Island", text: "The compact signal surface makes Marvi legible at a glance. Listening, thinking, responding, and completed states stay out of your way." },
  { icon: ShieldCheck, title: "Privacy", text: "Marvi is built local-first. Sensitive context starts close to you, with clear boundaries around what is processed, remembered, and shared." },
]

export default function DocsPage() { return <main className="docs-shell"><header className="docs-topbar"><Link className="brand" href="/"><Image src="/marvi-icon.png" alt="" width={28} height={28} /><span>MARVI / DOCS</span></Link><nav><Link href="/">BACK TO SITE</Link><a href={repositoryUrl} target="_blank" rel="noreferrer">SOURCE <Github aria-hidden="true" /></a></nav></header><div className="docs-intro"><p className="section-kicker">[ PUBLIC DOCUMENTATION / 01 ]</p><h1>Built to be<br /><em>around you.</em></h1><p>Marvi is a local-first voice and vision assistant for Windows. These docs are a clear introduction to what it is, what it can do, and how to begin.</p></div><div className="docs-layout"><aside className="docs-index"><p>ON THIS PAGE</p><a href="#capabilities">Capabilities</a><a href="#privacy">Privacy first</a><a href="#start">Get started</a></aside><div className="docs-content"><section id="capabilities"><p className="section-kicker">[ CAPABILITIES ]</p><h2>A system that feels<br /><span>like a presence.</span></h2><div className="docs-feature-grid">{sections.map(({ icon: Icon, title, text }) => <article key={title} className="docs-card"><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></section><section id="privacy" className="docs-callout"><ShieldCheck aria-hidden="true" /><div><p className="section-kicker">[ PRIVACY FIRST ]</p><h2>Your context belongs<br />to <span>you.</span></h2><p>Marvi’s product philosophy is simple: useful intelligence should not require giving up the feeling of a private space. Local-first operation, transparent controls, and deliberate memory keep you in charge.</p></div></section><section id="start" className="docs-start"><p className="section-kicker">[ GET STARTED ]</p><h2>Start with a<br /><span>single signal.</span></h2><p>Marvi is available for Windows through the public project releases. Download the latest bootstrap, then return here as the product evolves.</p><div className="hero-actions"><a className="button button-primary" href={`${repositoryUrl}/releases/latest/download/marvi-bootstrap.exe`}><Download aria-hidden="true" /> DOWNLOAD FOR WINDOWS</a><a className="button button-secondary" href={repositoryUrl} target="_blank" rel="noreferrer"><Github aria-hidden="true" /> VIEW SOURCE</a></div></section></div></div><footer id="contact"><div className="footer-brand"><Image src="/marvi-icon.png" alt="" width={22} height={22} /><span>MARVI</span></div><p>Open-source intelligence for Windows.</p><Link href="/">RETURN HOME <ArrowUpRight aria-hidden="true" /></Link><small>© 2026 MARVI. DOCUMENTATION.</small></footer></main> }
