import Image from "next/image"
import { ArrowUpRight, Command, Download, Github, Mic, Radio, ShieldCheck } from "lucide-react"

const repositoryUrl = "https://github.com/xRetr00/Marvi-OS"
const latestWindowsDownload = `${repositoryUrl}/releases/latest/download/marvi-bootstrap.exe`

const principles = [
  { icon: Radio, label: "ALWAYS PRESENT", title: "A quiet layer of intelligence", copy: "Marvi stays close without getting in the way. It notices the moment, understands the room, and waits until it has something worth saying." },
  { icon: ShieldCheck, label: "LOCAL BY DEFAULT", title: "Your world stays yours", copy: "Voice, vision, and memory begin on your machine. Marvi is designed around privacy as a starting point, not a setting to discover later." },
  { icon: Command, label: "ONE CLEAR SIGNAL", title: "Action without the noise", copy: "The Dynamic Island keeps the interaction compact. Listen, think, speak, act — every state is legible at a glance." },
]

export default function Home() {
  return <main className="shell"><header className="topbar"><a className="brand" href="#top" aria-label="Marvi home"><Image src="/marvi-icon.png" alt="" width={28} height={28} priority /><span>MARVI</span></a><nav aria-label="Primary navigation"><a href="#why">WHY MARVI</a><a href="#principles">PRINCIPLES</a><a href="#signal">THE SIGNAL</a></nav><a className="top-link" href={repositoryUrl} target="_blank" rel="noreferrer">SOURCE ON GITHUB <Github aria-hidden="true" /></a></header>
  <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> OPEN SOURCE / WINDOWS</p><h1>Present,<br /><em>when it matters.</em></h1><p className="lede">Marvi is an open-source, always-on voice and vision assistant for Windows. Built local-first, developed in public, and designed to stay quiet until it has something worth saying.</p><div className="hero-actions"><a className="button button-primary" href={latestWindowsDownload} aria-label="Download the latest Marvi bootstrap for Windows"><Download aria-hidden="true" /> DOWNLOAD FOR WINDOWS</a><a className="button button-secondary" href={repositoryUrl} target="_blank" rel="noreferrer"><Github aria-hidden="true" /> VIEW SOURCE</a></div><p className="release-note">LATEST RELEASE / MARVI-BOOTSTRAP.EXE</p></div><div className="hero-mark"><Image src="/marvi-icon.png" alt="Marvi app icon" width={360} height={360} priority /><div className="orbit-label label-a">VOICE / VISION</div><div className="orbit-label label-b">LOCAL RUNTIME</div><div className="crosshair" /></div></section>
  <section id="why" className="manifesto"><p className="section-kicker">[ A DIFFERENT KIND OF ASSISTANT ]</p><h2>Not another window.<br /><span>A presence in the room.</span></h2><p className="manifesto-copy">Marvi turns the distance between intention and action into something smaller. It listens for the wake word, sees what you see, and helps you move through the day without demanding another screen.</p></section>
  <section id="principles" className="principles"><div className="section-heading"><p className="section-kicker">[ HOW MARVI THINKS ]</p><span>03 PRINCIPLES</span></div><div className="principle-grid">{principles.map(({ icon: Icon, label, title, copy }) => <article className="principle" key={label}><Icon aria-hidden="true" /><p className="principle-label">{label}</p><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section id="signal" className="signal-section"><div><p className="section-kicker">[ THE DYNAMIC ISLAND ]</p><h2>One signal.<br /><span>Every state.</span></h2></div><div className="island-demo"><div className="island-pill"><span className="pulse" /> <span>LISTENING</span><Mic aria-hidden="true" /></div><div className="signal-lines"><span /><span /><span /><span /><span /></div><p>COMPACT / CONTENT-DRIVEN / CLEAR</p></div></section>
  <footer><div className="footer-brand"><Image src="/marvi-icon.png" alt="" width={22} height={22} /><span>MARVI</span></div><p>Open-source intelligence for Windows.</p><a href={repositoryUrl} target="_blank" rel="noreferrer">GITHUB / XRETR00 / MARVI-OS <ArrowUpRight aria-hidden="true" /></a><small>© 2026 MARVI. OPEN SOURCE. BUILT FOR PRESENCE.</small></footer></main>
}
