"use client"

import Image from "next/image"
import Link from "next/link"
import { useState } from "react"
import { ArrowUpRight, Brain, Eye, Github, Mic, Radio, ShieldCheck, Sparkles, Waves } from "lucide-react"

const repositoryUrl = "https://github.com/xRetr00/Marvi-OS"
const latestWindowsDownload = `${repositoryUrl}/releases/latest/download/marvi-bootstrap.exe`
const features = [
  { id: "voice", icon: Mic, label: "VOICE", title: "Talk naturally.", copy: "A wake word, a familiar voice, and an assistant that understands the difference between a request and a passing thought." },
  { id: "vision", icon: Eye, label: "VISION", title: "See the context.", copy: "Marvi can look with you: the screen, the room, the thing you are trying to understand right now." },
  { id: "memory", icon: Brain, label: "MEMORY", title: "Remember what matters.", copy: "A private memory layer makes conversations feel continuous without turning your life into a data product." },
]

export default function Home() {
  const [activeFeature, setActiveFeature] = useState("voice")
  const current = features.find((feature) => feature.id === activeFeature) ?? features[0]
  const CurrentIcon = current.icon

  return <main className="site-shell">
    <header className="topbar"><Link className="brand" href="#top" aria-label="Marvi home"><Image src="/marvi-icon.png" alt="" width={28} height={28} priority /><span>MARVI</span></Link><nav aria-label="Primary navigation"><a href="#capabilities">CAPABILITIES</a><a href="#signal">THE SIGNAL</a><Link href="/docs">DOCS</Link></nav><a className="top-link" href={repositoryUrl} target="_blank" rel="noreferrer">OPEN SOURCE <Github aria-hidden="true" /></a></header>
    <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> OPEN SOURCE / WINDOWS / 01</p><h1>Present,<br /><em>when it matters.</em></h1><p className="lede">Marvi is an open-source, always-on voice and vision assistant for Windows. Built local-first, developed in public, and designed to stay quiet until it has something worth saying.</p><div className="hero-actions"><a className="button button-primary" href={latestWindowsDownload}><Sparkles aria-hidden="true" /> DOWNLOAD FOR WINDOWS</a><Link className="button button-secondary" href="/docs">EXPLORE THE DOCS <ArrowUpRight aria-hidden="true" /></Link></div><p className="release-note">LATEST RELEASE / MARVI-BOOTSTRAP.EXE</p></div><div className="hero-mark"><div className="hero-grid" /><Image src="/marvi-icon.png" alt="Marvi app icon" width={360} height={360} priority /><div className="orbit-label label-a">VOICE / VISION</div><div className="orbit-label label-b">LOCAL RUNTIME</div><div className="crosshair" /></div></section>
    <section className="marquee" aria-label="Marvi capabilities"><span>LISTEN</span><span>SEE</span><span>REMEMBER</span><span>ACT</span><span>STAY PRIVATE</span></section>
    <section id="why" className="manifesto"><p className="section-kicker">[ A DIFFERENT KIND OF ASSISTANT ]</p><h2>Not another window.<br /><span>A presence in the room.</span></h2><p className="manifesto-copy">Marvi turns the distance between intention and action into something smaller. It listens for the wake word, sees what you see, and helps you move through the day without demanding another screen.</p></section>
    <section id="capabilities" className="capabilities"><div className="section-heading"><p className="section-kicker">[ WHAT MARVI CAN DO ]</p><span>01 — 03</span></div><div className="feature-layout"><div className="feature-tabs">{features.map(({ id, icon: Icon, label }) => <button key={id} className={activeFeature === id ? "feature-tab active" : "feature-tab"} onClick={() => setActiveFeature(id)} aria-pressed={activeFeature === id}><Icon aria-hidden="true" /><span>{label}</span><ArrowUpRight aria-hidden="true" /></button>)}</div><article className="feature-detail"><div className="feature-number">0{features.findIndex((feature) => feature.id === activeFeature) + 1}</div><CurrentIcon aria-hidden="true" /><h3>{current.title}</h3><p>{current.copy}</p><div className="feature-meter"><span /><span /><span /><span /><span /></div><small>DESIGNED FOR PRESENCE / BUILT FOR CONTEXT</small></article></div></section>
    <section id="principles" className="principles"><div className="section-heading"><p className="section-kicker">[ HOW MARVI THINKS ]</p><span>03 PRINCIPLES</span></div><div className="principle-grid"><article className="principle"><Radio aria-hidden="true" /><p className="principle-label">ALWAYS PRESENT</p><h3>A quiet layer of intelligence</h3><p>Marvi stays close without getting in the way. It notices the moment and waits until it has something worth saying.</p></article><article className="principle"><ShieldCheck aria-hidden="true" /><p className="principle-label">LOCAL BY DEFAULT</p><h3>Your world stays yours</h3><p>Voice, vision, and memory begin on your machine. Privacy is the starting point, not a setting to discover later.</p></article><article className="principle"><Waves aria-hidden="true" /><p className="principle-label">ONE CLEAR SIGNAL</p><h3>Action without the noise</h3><p>The Dynamic Island keeps interaction compact. Every state is legible at a glance, from listening to done.</p></article></div></section>
    <section id="signal" className="signal-section"><div><p className="section-kicker">[ THE DYNAMIC ISLAND ]</p><h2>One signal.<br /><span>Every state.</span></h2><p className="signal-copy">A small surface for a big system. Marvi communicates through a focused, glanceable signal instead of another dashboard.</p></div><div className="island-demo"><div className="island-pill"><span className="pulse" /><span>LISTENING</span><Mic aria-hidden="true" /></div><div className="signal-lines"><span /><span /><span /><span /><span /></div><p>COMPACT / CONTENT-DRIVEN / CLEAR</p></div></section>
    <section className="closing-cta"><p className="section-kicker">[ BEGIN WITH MARVI ]</p><h2>Make room for<br /><span>the useful.</span></h2><div><p>Read how Marvi works, explore the capabilities, or download the latest Windows build.</p><Link className="button button-primary" href="/docs">READ THE DOCS <ArrowUpRight aria-hidden="true" /></Link></div></section>
    <footer id="contact"><div className="footer-brand"><Image src="/marvi-icon.png" alt="" width={22} height={22} /><span>MARVI</span></div><p>Open-source intelligence for Windows.</p><a href={repositoryUrl} target="_blank" rel="noreferrer">SOURCE / RELEASES <ArrowUpRight aria-hidden="true" /></a><small>© 2026 MARVI. OPEN SOURCE. BUILT FOR PRESENCE.</small></footer>
  </main>
}
